### ISSUE TITLE
food-tracker 페이지 UI 구현

### ISSUE THREAD

**Issue by SeokHoChoi** [SeokHoChoi/allini#57]
food-tracker 페이지
  - [x] food-tracker 에서 탭키 구현 및 기본 탭키 설정 리다이렉팅을 위한 routes 수정
  - [x] tab 컴포넌트 재사용을 위해 register 페이지 컴포넌트에서 TabComponent 분리 및 food-tracker에 적용
  - [x] today tab (오늘의 밥그릇)

PR 사이즈를 위해 아래의 페이지 구현은 다음 ISSUE 로 이동합니다.
- food-treats tab (밥그릇 모아보기)
- report tab (밥그릇 기록장)
