### ISSUE TITLE
food-tracker 페이지 내의 밥그릇 모아보기 탭 UI 구현

### ISSUE THREAD

**Issue by SeokHoChoi** [SeokHoChoi/allini#59]
### 관련 ISSUE 및 PR
#57, #58 

### 밥그릇 모아보기 UI 구성요소
   - [x] 상단 검색 안내 및 등록하기 버튼
   - 카드 컴포넌트 
     - [x] 좌측 이미지
     - [x] 우측 INFO 및 알림 배지 구현 
   - [x]  Today (오늘의 밥그릇) 탭 페이지 내의 사이드바 z-index 조정
