### ISSUE TITLE
food-tracker 페이지 내의 밥그릇 기록장(Report) 탭 UI 구현 - 

### ISSUE THREAD

**Issue by SeokHoChoi** [SeokHoChoi/allini#63]
- ### **오전/오후 식단관리 컴포넌트**
  - [x] 원형 그래프 UI 구현 (컴포넌트 분리)
  - [x] 음식 추가 관련 UI 구현
- ### **성분 조회 컴포넌트**  
  - [x] 바 차트 구현 (각 성분 비율 표시)
  - [x] 각 성분의 퍼센티지를 별도 컴포넌트로 분리

### **관련 ISSUE**
- #61 
- #59 
- #57
